<a href="https://colab.research.google.com/github/safaltasaxena/ml-learning-mini-projects/blob/main/k-fold-cross-validation/K_Fold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

k fold cross validation

which model should i use to solve this particular model??

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [ ]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [ ]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9851851851851852

In [ ]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9518518518518518

the number of time i run the train test split cell the number of times my data gets changed and then accuiracy keeps on changing

so just getting score once u cant say anyhting about it

thats where we intorduce k fold cross validation

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)#telling model how many folds i need to make of dataset
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
#example
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):#returns iterator
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [ ]:
#example
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
#straitfiedfold is better than fold cz it divides folds uniformly
scores_l =[]
scores_svm=[]
scores_rf=[]
#creating these arrays to store the scores from each model
for train_index,test_index in kf.split(digits.data):
#since we have 3 folds the for loop will repeat itself 3 times.
   x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
   scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
   scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
   scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [ ]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [ ]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [ ]:
scores_rf

[0.9298831385642737, 0.9499165275459098, 0.9198664440734557]

well writing this much code is messy to compare so rather now we will direct import and write


In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93611111, 0.90833333, 0.96100279, 0.9637883 , 0.92479109])

we compared with diff methods we can change parameters of 1 method say rf like we put estimators as 30 so then we can compare within 1 method diff parameter that is known as "PARAMETER TUNING"